const store = [
    {
        key: "Arrojar",
        description: "Para lanzar una filosa daga, pasando por una bomba de alquitrán hasta una gigantesca roca que caerá sobre todos esos despistados trasgos, deberás utilizar esta Habilidad. Al momento de declarar la acción y lanzar el objeto, a la tirada de 1d10 se le debe sumar el bonificador según el nivel de Arrojar. Si intentas arrojar objetos pesados, deberás hacer también una tirada de 1d10 de Fuerza. Consulta también el Capítulo 6: Combate, para más información sobre arrojar objetos y una tabla de dificultad por distancia."
    },
    {
        key: "Artes Circenses",
        description: "Todos los payasos, juglares, bufones y hasta los estafadores saben coordinar sus brazos y hacer unos cuantos trucos. Un experto en estas artes podría hacer equilibrio sobre una cuerda floja para pasar de un lado a otro, o escabullirse en un pequeño lugar contorsionándose para caber. Hacer piruetas para pasar de un lado a otro evitando alambres que activarían alarmas, atrapar objetos lanzados, hacer malabares cada vez más peligrosos y hasta trucos de magia (sin magia, claro está). Dependiendo de lo que se haga, la dificultad de la tirada aumentará, no es lo mismo malabarear tres pelotitas que cuatro espadas afiladas."
    },
    {
        key: "Artística",
        description: "El personaje podrá interferir en la cultura y entretenimiento de la sociedad."
    },
    {
        key: "Carterismo",
        description: "Esta Habilidad es esencial para poder robar. Sustraer cosas de un inventario, tomar bolsas de oro prestadas de un bolsillo u objetos de un lugar determinado con absoluta discreción requiere “Carterismo”. Por supuesto, para robar algo que una persona tiene consigo, el amigo de lo ajeno deberá realizar una tirada de (1d10 + Des + Carterismo). El resultado de esta tirada se deberá enfrentar a una tirada de quien es robado (1d10 + Des + Percepción). Si el objetivo logra superar tu resultado, te descubrirá o al menos descubrirá que le falta algo. Si logras ganarle la tirada enfrentada, tu robo ha tenido éxito, aunque más adelante podría darse cuenta que le han robado (o pensar que lo ha perdido). Si la persona te está viendo, te detectará directo."
    },
    {
        key: "Cerrajería",
        description: "Abrir cerraduras es un arte, ilegal, pero arte al fin. Solo los más habilidosos ladrones podrán con solo unas ganzúas hacer saltar hasta la más sofisticada cerradura enana. Cada cerradura tiene una tirada de dificultad específica que el personaje deberá superar al intentar abrirla realizando una tirada de (1d10 + Sab + Cerrajería); además puedes sumarle el bonificador que te dé algún arma de ladrón que estés usando para violar esa cerradura. Cabe destacar que hay cerraduras protegidas con conjuros y no se pueden abrir con nada. Si el personaje pierde la tirada por 5 puntos o más del resultado a batir, su ganzúa o herramienta se romperá. Consulta el Capítulo 9: el Mundo para saber más sobre aperturas y consultar la tabla."
    },
    {
        key: "Combate con X arma",
        description: "Cualquiera puede tomar un cuchillo y enterrárselo en el estómago a un pobre distraído. Pero cuando tu arma es un mandoble gigante mágico, un poderoso arco o una inefable hacha y estás peleando contra un gigantesco dragón de tres cabezas, necesitarás saber maniobrarla o perderás mínimo un dedo. Para eso, la Habilidad “Combate con X Arma” te permitirá aprender un poco más del arte de la lucha con las distintas armas que hay y obtener un bonificador al acierto con el arma que manejes dependiendo del nivel que tengas esta Habilidad. Se puede elegir múltiples veces y lo tendrás que hacer si deseas aprender a pelear con algún tipo de arma diferente. Como podrás ver en el Capítulo 6: Combate, existen muchos tipos de arma como puede ser una daga, hacha de mano, mazo de guerra, ballesta, gomera, bastón o varita. Aunque sepas utilizar espadas largas, deberás aprender sobre espadas cortas. Al comprar la Habilidad, podrás anotarla en la hoja de personaje como “Combate con Mandoble”, cambiando el mandoble por el arma que hayas aprendido. Para el combate marcial, esta Habilidad también sirve para las tiradas de acertar al golpear a un enemigo. Por lo tanto, podrás comprarla y anotarla como “Combate Marcial”. No se pueden hacer tiradas de maña con esta Habilidad."
    },
    {
        key: "Coquetear",
        description: "Nadie se salvará de esto ni en un juego de rol. Coquetearle a alguien no significa siempre querer llevárselo a “lo oscurito” o enamorarlo directamente, sin escalas. También sirve para caerle bien a alguien de forma independiente de su orientación sexual, siempre y cuando las intenciones sean explícitas desde un principio. Coquetear podría ser útil para liberar a tus compañeros de prisión, aprovechando los instintos bajos de un guardia que cae fácilmente ante una seductora pierna para robarle las llaves de la celda, o ganarse la confianza de una duquesa para poder saber dónde se encuentra la valiosa joya. Estas son todas cosas donde el Discurso no alcanza, va más allá de la dialéctica y requiere actitudes de seductor y casanova. La tirada del coqueteo es de (1d10 + Car + Coquetear), pero pueden sumarse o restarse diversos modificadores, por ejemplo el atractivo o rechazo a un Pueblo o reino específico, el sexo, un regalo (un ramo de flores, de lo más clásico) y otros factores que puedan hacerte atractivo o repugnante dependiendo de los gustos del PNJ (esto queda a merced del MJ). Incluso podrías combinarlo con otras Habilidades si recitas un poema (Artística) o cantas una canción (Interpretar). Trata de mantener una buena comunicación con tu MJ para poder llevar una situación de coqueteo lo más cómoda posible para todo el grupo en el juego."
    },
    {
        key: "Correr",
        description: "Algunas veces está bien dejar todo donde está y salir pitando de allí, esto podría salvarte la vida en varias ocasiones. Pues que se enfrente otro contra ese troll de las montañas o ¿qué harás contra una estampida de toros que viene hacia ti? Pues correr por supuesto. Y es aquí donde entra esta Habilidad. Aunque no sirva en combate, fuera de él o para retirarse, te permite dejar todo a un lado y salir como perro del lugar. Para correr solo debes definir tu acción, no hacer nada más y superar la tirada de dificultad que el MJ declare para tener éxito en la huida. La tirada de “Correr” para la velocidad que podrás alcanzar es de (1d10 + Correr + Des) y para mantener la velocidad es de (1d10 + Correr + Vol). En algunos casos puede que te persigan, por lo tanto se reemplaza la dificultad por dos tiradas enfrentadas; si ganas huirás, si pierdes te atraparán. Consulta el Capítulo 6: Combate para saber más de las persecuciones a pie y en vehículo. Se pueden hacer tiradas normales si se carece de esta Habilidad, pero deberás omitir el bonificador de Correr o restarlo si es el caso.  "
    },
    {
        key: "Discurso",
        description: "El personaje es cada vez más ducho en el arte del habla y el engaño, pudiendo convencer a otras personas a base de mentiras o verdades a medias para su (se combina con persuasión), pero también sirve para situaciones que requieran retórica como en la política, resolver conflictos pacíficamente o para negociar y regatear un buen precio al comerciante de turno. Acompañado de las palabras elegidas para dar, el personaje podrá hacer una tirada de “Discurso” (1d10 + Discurso + Car). Si el oponente posee Percepción, podrá hacer una tirada enfrentada contra dicho resultado para detectar el engaño. Si la supera, podrá saber si le miente o no con certeza. Sino, se quedará en la duda o directamente no se dará cuenta. Por otro lado, esta Habilidad sirve para dar discursos emotivos y bellos, dignos de un poeta, para motivar, enamorar o subir la moral a la tropa. También sirve para saber recabar información sabiendo cómo hablar con las personas para obtener detalles, rumores o acceder a los secretos bajos de la ciudad, encontrando contactos y otras sorpresas. La tirada tanto para mentir, como para hablar con las personas y dar discursos es (1d10 + Discurso + Car). La dificultad está a merced del MJ dependiendo el objetivo final del discurso."
    },
    {
        key: "Doma",
        description: "Aunque no podamos usar el idioma común de cada Pueblo para comunicarnos con los animales, si podremos hacer uso de un lenguaje más corporal para poder entendernos. Doma es una habilidad muy completa para tratar con los animales. Con ella, el personaje podrá interactuar con algún animal o bestia, dar órdenes, enseñar trucos sencillos y hasta hacerse amigos para que lo acompañen por un breve periodo de tiempo. También se puede utilizar Doma para hacer huir a un animal salvaje o a un grupo de ellos que quieran atacarte, para evitarte una pelea. La tirada para esto será de (1d10 + Doma + Car) y algún otro bonificador, como por ejemplo si es un animal inteligente, adiestrado o amigo del personaje. Aunque no se sumen los bonificadores, esta Habilidad se puede combinar con “Saber Bestiario” para poder encontrar un punto débil para la criatura (por ejemplo, que le gusta comer), o llevarte mejor con tu montura con Montar. No se pueden hacer tiradas de maña de esta Habilidad a menos que el animal sea uno adiestrado previamente."
    },
    {
        key: "Escalar",
        description: "Si necesitas trepar árboles, casas, murallas, escalar montañas, torres, volcanes en erupción o a un enorme gigante para apuñalarlo en el ojo, esta es tu habilidad. “Escalar” se basa en un solo Atributo (el que más alto tengas): Destreza o Fuerza, fuera de eso funciona normalmente. La tirada para poder escalar sea única o periódica es de 1d10 + Escalar + Des o Fue) y puedes agregarle otros bonificadores como un equipo de escala (pudiendo ser sogas, ganchos, equipo de escala, etc) Puedes consultar el Capítulo 9: el Mundo para aprender más sobre escalar cosas."
    },
    {
        key: "Esconderse",
        description: "No puedes correr, pero si te puedes esconder. Aceptémoslo, no solo van a tener que luchar a cada rato, la mitad de ese tiempo necesitaran correr por sus vidas. Pero mejor que correr es esconderse, y cualquiera puede esconderse detrás de un árbol o en un pozo, pero los personajes más especializados saben cómo hacerlo bien y ser casi indetectables en cualquier sitio. No tener esta habilidad aprendida no significa penalizador alguno, pero cuanto mejor se esconda el personaje, mayor dificultad le otorgará al enemigo encontrarlo, que tendrá que hacer una tirada enfrentada a tu tirada de (1d10 + Int + Percepción) si tiene el conocimiento de que estás por ahí escondido. Si no sabe de tu existencia, solamente el 1d10. Tu tirada para esconderte es de (1d10 + Esconderse + Int) y el MJ puede agregar un bonificador por el lugar donde te has escondido. Además, esta Habilidad también es útil para confeccionar disfraces, sea para pasar desapercibido (por ejemplo, una túnica para infiltrarse en una secta loca) o un camuflaje para el bosque."
    },
    {
        key: "Fortaleza",
        description: "Además de tener fuerza, una persona debe aprender a usarla. Fortaleza es una Habilidad que permite canalizar mejor las fuerzas y la energía física del personaje para usarlo de una forma superior y no solo en el acto bruto. Cuando el héroe cae víctima de un ataque o trampa cuyo efecto sea un control de masas de una fuente física, este (si tiene aprendida esta Habilidad) tendrá derecho a una tirada de Salvación de fortaleza para evitarlo o salvarse en cada turno (si no la posee, deberá esperar al siguiente, ver Capítulo 6: Combate). La tirada es de (1d10 + Fortaleza + Fuerza) contra la dificultad que el MJ decida o el origen del control de masas establezca según las reglas. El control de masas físico puede ser agarres de otras personas, trampas físicas como redes, sogas, cadenas, arenas movedizas, aplastamiento, enraizamientos de fuentes físicas o conjuros mágicos cuyo efecto final esté ligado a lo físico (un ejemplo es el Tentáculos Inmundos del Nigromante). No se pueden hacer tiradas de maña de esta Habilidad."
    },
    {
        key: "Idioma",
        description: "Existen muchos idiomas a lo largo del Aeternus, y el personaje puede aprender casi todos si encuentra el maestro de cada uno. Por norma general, los personajes comienzan sabiendo uno o dos idiomas: universal (el idioma común en todas las lenguas) y el que hablen en su comunidad (Keli-ata o Rakshasa por ejemplo). Los personajes con estos idiomas de nacimiento se considera que lo tienen en “nivel 6” por ser nativos. Pero también pueden aprender idiomas ajenos a ellos sean modernos o antiguos (ver Capítulo 9: el Mundo para encontrar todos los idiomas y lenguajes). El personaje podrá elegir esta Habilidad varias veces por cada idioma nuevo que desee aprender. Se pueden hacer tiradas para intentar traducir o escuchar cosas complejas o asociar un idioma moderno a uno antiguo (por ejemplo, el Keli-Ata actual de los Enkelis con el Keli-Ata antiguo), haciendo una tirada de (1d10 + Idioma + Int) y si se tiene una comparación, agregar algún bonificador de Saber."
    },
    {
        key: "Inmunidad",
        description: "Los personajes pueden desarrollar una resistencia a las diversas toxinas y enfermedades que existen en el Aeternus. Tanto los venenos como enfermedades leves, intermedias y graves pueden curarse a su tiempo con el antídoto, medicina, conjuro o tratamiento adecuado (exceptuando los que son fatales), sin embargo puede que no siempre tengas al alcance de la mano estos recursos y tengas un camino largo hacia ellos (ver Capítulo 6: Combate para más información sobre enfermedades y venenos). Haciendo una tirada de Salvación de Inmunidad al contraer la enfermedad o veneno (1d10 + Inmunidad + Con) contra cierta dificultad, podrás evitarla desde el inicio. Si la fallas, podrás continuar haciendo tiradas por turno para evitar que la enfermedad o veneno te afecte y avance, también de (1d10 + Inmunidad + Con) contra la dificultad de la ponzoña o enfermedad establecida por el MJ. También se puede sumar otros bonificadores de medicinas y preparados que si bien no son antídotos o curas, sirven para fortalecer la salud (como un té de limón). Si la tirada se realiza con éxito podrás soportar un turno más sin problemas, caso contrario avanzará normalmente. Recuerda que una vez enfermo o envenenado, Inmunidad no te curará; tendrás que buscar la medicina o antídoto. No se pueden hacer tiradas de maña de esta Habilidad."
    },
    {
        key: "Interpretar",
        description: "Tanto para el gozo del arte como para la manipulación de la magia misma por medio de las vibraciones, cualquiera que sea su objetivo, Interpretar le dará la oportunidad al personaje de elegir un instrumento musical o cantar con su propia voz por cada vez que se aprenda la Habilidad (pues puede elegirse múltiples veces por cada uno). Hay múltiples instrumentos en el Aeternus, como el laúd, la guitarra, los platos, la flauta, tambores y todos los que el MJ decida colocar que cuelen con la ambientación (adiós theremín). Por cada nivel de esta Habilidad, el personaje tocará mucho mejor el instrumento musical aprendido, pudiendo así interpretar notas, canciones y sonatas hermosas y bellas para lograr diversos cometidos desde enamorar a una dama, entretener a un grupo de personas o tocar “a la gorra” en la calle. Las tiradas para tocar o cantar, sea en un auditorio, la calle o para invocar el poder mágico de la música (Bardo), son de (1d10 + Interpretar* + Car) contra una dificultad de concentración establecida por el MJ."
    },
    {
        key: "Intimidar",
        description: "¿Conocen el dicho “perro que ladra no muerde”? En este caso no podríamos estar tan seguros, pero muchas veces las personas no quieren pelear, por lo que recurren a estrategias de dominación naturales, como la intimidación por ejemplo. Esto les servirá mucho a aquellos personajes que tengan mucho músculo pero poco seso para poder engañar o diseñar planes que eviten un confrontamiento u obtener información sin tener que recurrir a la tortura. Quien quiera intimidar a una persona, deberá hacer una tirada enfrentada de (1d10 + Intimidar + Fue) y añadir otros bonificadores aleatorios como puede ser poseer armas poderosas para asustar, un posterior enfrentamiento o alguna mala fama que tenga el PJ. Quien sea intimidado, deberá realizar una tirada de (1d10 + Voluntad) más otros bonificadores situacionales para evitar ser intimidado. Si el personaje tiene éxito, será más fácil lograr el cometido concreto (hacer huir a alguien, darle miedo en batalla o sacarle información sin lastimarle).   "
    },
    {
        key: "Medicina",
        description: "Cuando tus tripas ven la luz, desearás ver a alguien que tenga esta Habilidad aprendida; solo recuéstate y deja al médico trabajar. Para tratar una herida, el médico deberá realizar una tirada de (1d10 + Medicina + Sabiduría) y agregar cualquier bonificador extra, como puede ser alguna herramienta de médico, ayuda mágica de regeneración o un lugar donde atenderlo. La dificultad de la herida a curar dependerá de qué tipo sea (leve, intermedia o grave) y lo que el MJ disponga. Las heridas de muerte no se pueden curar, pero algunas si se pueden mantener para retrasarla, la dificultad de esta será a discreción del MJ. Ten cuidado con las tiradas de maña, pues fallar gravemente podría matar a tu paciente (puedes ver el Capítulo 6: Combate para saber más sobre heridas y curación)."
    },
    {
        key: "Metamagia",
        description: "Al igual que Fortaleza, esta Habilidad de Salvación es excelente para evadir los estragos causados por los ataques mágicos. La Metamagia es un arte de defensa contra las energías de control de masas. Cuando el personaje es alcanzado por un Conjuro, una trampa mágica o cualquier ataque cuyo origen sea mágico y se tratase de un efecto de control de masas, esta Habilidad entrará en acción. Al instante que el control de masas mágico caiga sobre tu personaje (o en los turnos posteriores si esto es posible), podrás realizar una tirada de Metamagia solo si tienes la Habilidad aprendida para poder librarte del efecto enemigo contra el valor de la tirada de concentración del oponente o la dificultad de la trampa establecida por el MJ. La tirada es de (1d10 + Metamagia + Inteligencia). Esta Habilidad no solo es esencial para las clases mágicas, sino también hace una excelente combinación con la Aptitud Contraconjuros (ver más abajo). Para saber más sobre control de masas mágico o físico, visita el Capítulo 6: Combate. No se pueden hacer tiradas de maña de esta Habilidad."
    },
    {
        key: "Montar",
        description: "Un personaje sobre una montura es mucho más destructor que uno a pie (y además llega más rápido a todos lados). Sin embargo, para poder subirte a una montura se requiere que el PJ aprenda lo mínimo sobre su manejo y la técnica de monta, de lo contrario solo podrá subirse como acompañante, pues es muy probable que cuando intente manejar a la criatura, esta se retobe y lo lance de la silla o que el mismo se caiga de ella sin mayor esfuerzo. Dependerá de cada tipo de montura y criatura el nivel necesario o puntos invertidos en la Habilidad para ser competente al montarla. Las tiradas de esta Habilidad solo se realizan al hacer maniobras peligrosas o para mantenerse estabilizado (1d10 + Montar + Des) contra la dificultad que el MJ defina. Para tener un mejor trato y entendimiento con tu montura, puedes utilizar Doma."
    },
    {
        key: "Nadar",
        description: "Esta Habilidad es similar a Correr, pero en principio el primer nivel te enseña a nadar. Si tu personaje no tiene el nivel aprendido de Nadar, pues efectivamente no podrá hacerlo, tendrá que hacer una tirada de maña solamente para no ahogarse por cada ronda que pase en el agua. Por otro lado, trata de no darte un chapuzón con una armadura intermedia o pesada puesta, pues te hundirás como una roca. Al comenzar a nadar, ir de un punto a otro o hacer diversas acciones en el agua no requerirán tiradas elevadas, pero a medida que el personaje se encuentre nadando, su cuerpo se cansará y cada vez le costará más y más, la dificultad irá en aumento hasta que ya no pueda más (esto lo definirá el MJ). La tirada de “Nadar” para la velocidad que podrás alcanzar es de (1d10 + Nadar + Des) y para mantenerse constante es de (1d10 + Nadar + Vol). Si estás en una persecución, se aplican las mismas reglas que en tierra."
    },
    {
        key: "Percepción",
        description: "Las personas más avispadas y atentas al mundo que les rodea son altamente perceptivas. Pueden oír el zumbido de una abeja a varios metros, oler podredumbre antes que otros, ver donde la vista normal no llega, utilizar el tacto para guiarse en la oscuridad, sentir mediante el gusto los ingredientes que componen lo que está comiendo y presentir cuando algo no anda bien. Esta Habilidad se utiliza para cualquier prueba que involucre estos cinco sentidos y además, para detectar las mentiras (ver Habilidad Discurso). Tocar, observar, escuchar, probar y oler. Cuando requieras hacer una tirada para, por ejemplo, ver detalles en una habitación que te llevarán a un escondrijo secreto, oír los murmullos del otro lado de la puerta, oler un muerto escondido o sentir el amargo veneno en tu comida, deberás hacer una tirada de (1d10 + Percepción + Int) contra la dificultad que el MJ decida. Algunas cosas como catalejos pueden darte bonificadores especiales. Si tienes motivos para creer que algún personaje te está mintiendo, podrás tener derecho a una tirada contra su tirada de Discurso si tuviese la Habilidad, o el mismo MJ podría hacerte la tirada automática e informarte que detectas una mentira. También, es probable que tu personaje sienta que “algo no anda bien”. Esto es un recurso utilizable por el MJ en caso que quiera darte alguna ventaja."
    },
    {
        key: "Reflejos",
        description: "Los más fuertes dan las más duras batallas, pero los más rápidos son las que sobreviven a ellas. Reflejos es una Habilidad de Salvación y como tal, no se pueden hacer tiradas de maña con ella. Hay muchas ocasiones en las que tu vida podría acabarse en tan solo un instante, pero para eso está “Reflejos”. Si algún disparo de una catapulta en combate se ha descontrolado y viene hacia ti, o un ataque sorpresa salido de la nada, un techo que se derrumba sobre tu cabeza, el suelo que cae hacia terribles pinches o algún objeto o cosa que sea perceptible a simple vista y te dé un margen de reacción mínimo, podrás hacer una tirada de Salvación de Reflejos para poder esquivarla. Aunque no necesitas esta Habilidad para hacer tu tirada contra cosas que podrían matarte, teniéndola tendrás derecho a hacerlas en situaciones que no te eliminen, pero puedas recibir un gran daño. A menudo, esta tirada será pasiva y el MJ la hará por ti, pero otras veces deberás hacerla tú y será de (1d10 + Reflejos + Des) contra la dificultad establecida por el MJ. En el Capítulo 6: Combate, podrás ver más sobre las tiradas de Salvación y esquiva. No se pueden hacer tiradas de maña en esta Habilidad."
    },
    {
        key: "Resistir calor",
        description: "Esta es una más del abanico de las Habilidades de Salvación. Al igual que todas ellas es pasiva y solo entra en juego cuando el personaje se encuentra en un lugar donde la temperatura sea elevada. El calor en un cuerpo (sobre todo en los de los Pueblos elegibles) puede causar estragos como deshidratación, mareos, cansancio, desmayos, alucinaciones, heridas físicas en formas de quemaduras o mal funcionamiento de órganos, quemaduras, incineración y hasta la muerte, lo que deviene también en pérdida de Puntos de Resistencia y otros penalizadores. Sin embargo, el personaje que tenga esta habilidad podrá realizar tiradas de Salvación de (1d10 + Resistir Calor + Voluntad) para poder sobrellevar los problemas de una temperatura elevada. Ten en cuenta que recibir un Conjuro de daño directo de Fuego no te dejará hacer una tirada de Salvación de Resistir Calor, pero si algún Conjuro que afecte de forma secundaria; prenderse fuego tampoco te dejará resistir el frío. En el Capítulo 9: el Mundo, podrás ver más sobre el calor, los climas y sus efectos. En este caso, si se pueden hacer tiradas de maña en esta Habilidad."
    },
    {
        key: "Resistir frío",
        description: "Caso contrario al calor, para enfrentarse a los climas más fríos el personaje necesitará esta Habilidad. Al igual que la otra, Resistir Frío es una Habilidad de salvación y por lo tanto solo se podrá hacer uso cuando el personaje sufra los embistes del frío. Hay que tener en cuenta que los Conjuros de daño directo cuya fuente sea Hielo no te dejarán hacer una tirada de Salvación, como tampoco quedar congelado en un bloque de hielo mágico, pero si Conjuros que bajen temperaturas como efectos colaterales. El frío hará que el cuerpo se quede sin fuerzas, las extremidades comiencen a congelarse y los nervios se adormezcan, incluso dejar de sentir hasta la muerte por hipotermia. La tirada para soportar el frío es de (1d10 + Resistir Frío + Voluntad), pero también se pueden hacer tiradas de maña."
    },
    {
        key: "Saber bestiario",
        description: "El conocimiento es poder, aquellos que se pasan su tiempo en la biblioteca estudiando a las criaturas que en un futuro se podría cruzar tendrán su recompensa en el combate. Muchos personajes al perseguir sus aventuras, en el camino se enfrentan a bestias que jamás han visto, y como no es de su conocimiento algunos combates pueden salir mal y perderse. Pero otros aventureros estudian a sus enemigos y tienen el conocimiento de que hacer en el caso de verlos cara a cara. Cuando una criatura desconocida se hace presente ante un aventurero con esta habilidad aprendida, este podrá realizar de forma automática al momento de verla una tirada de Saber Bestiario de (1d10 + S. Bestiario + Sab) para identificar a la criatura y obtener cierta información del Manual Bestiario o del MJ directamente que podrá usar de forma que no entre en el metajuego. Hay criaturas que pueden reconocerse sin tirada alguna por la cotidianidad, como las criaturas de granja y las bestias autóctonas del reino. Si el personaje derrota a la criatura desconocida, podrá servirse de la información del manual Bestiario para futuros encuentros con otras del mismo tipo. No pueden hacerse tiradas de maña."
    },
    {
        key: "Saber geográfico",
        description: "Los aventureros no solo se basan en su magia o la fuerza de sus brazos, también deben utilizar su sabiduría en el mundo como también todos los recursos que se tengan para poder sobrevivir. Y saber dónde uno está parado o a donde uno debería ir es esencial en la vida. Aquellos que tengan esta Habilidad obtienen una gran ventaja al resto, aprendiendo a leer mapas, a entender el entorno, a saber las diversas ubicaciones de los diversos lugares como las cordilleras, caminos, volcanes, montañas, lagos, etc. Será casi imposible que los PJs con Saber Geográfico se pierdan en un bosque o lugar, pudiendo encontrar incluso atajos hacia sus destinos. Por otro lado, también sabrán sobre la flora y fauna de las diversas locaciones, zonas históricas y populares, haciendo tiradas de (1d10 + S. Geográfico + Sab), cuya información recibida por parte del MJ dependerá de la cantidad del valor de la tirada ¡Cuánto más alto, mejor! Recuerda que cada mapa de ubicación o de navegación marítima requiere un determinado nivel de esta Habilidad para poder interpretarlo de forma automática (no hace falta hacer tirada, solo cumplir el requisito) y esto es muy útil para encontrar las ubicaciones de tesoros y mazmorras. Solo se pueden hacer tiradas de maña cuando se tenga algún mapa básico de la zona, brújulas, la Aptitud Supervivencia o alguna herramienta de guía. Esta Habilidad permite hacer tiradas de maña, pues el entorno natural es frecuentado a menudo por casi todas las criaturas en un mundo medieval."
    },
    {
        key: "Saber historia",
        description: "De la historia se debe aprender porque la existencia no se trata de una línea recta, sino de algo circular y los hechos del pasado que llevaron a las guerras y miserias siempre vuelven a aparecer cuando estos se ignorar. Y de la historia también se pueden tomar las soluciones a conflictos actuales. Los PJs que aprendan esta habilidad podrán realizar tiradas de conocimiento sobre lugares, personas famosas, objetos y hasta entidades, una tirada de 1d10 + S. Historia + Sab. Dependiendo del valor de la tirada, el MJ le dará al jugador una determinada cantidad de información histórica que crea justa. A simple vista pareciera que esta habilidad no sirve para nada, pero en realidad es muy útil para enfrentarse a intrigas y poder encontrar diversas soluciones a los problemas propuestos en la aventura. Además, el personaje podrá sumar el bonificador de esta Habilidad a las tiradas de saber popular que haga e incluso cuando intente recordar algo utilizando la memoria. No se pueden hacer tiradas de maña de esta Habilidad."
    },
    {
        key: "Saber mágico",
        description: "Una cosa es tener el poder, y la otra es saber manipularlo. Saber Mágico es una excelsa Habilidad no solo para los magos, sino para todos los aventureros. Primeramente, sirve para poder hacer uso de los poderosos artefactos mágicos (ver Capítulo 8: Economía). Por otro lado los PJs que tengan al menos el primer nivel de esta Habilidad podrán saber que hechizo está conjurando o ha conjurado el enemigo, pudiendo obtener automáticamente información del MJ para poder contrarrestar el efecto. Por último y no menos importante, los héroes con Saber mágico podrán utilizar los diversos objetos mágicos antiguos escondidos en todos lados para extraer su poder y servirse de él. También sirve para detectar algún rastro mágico en un objeto y hacer más fácil las tiradas de Identificar o de desarmar trampas de índole mágica. Las tiradas para esta Habilidad son (1d10 + S. Mágico + Sab). Solo las clases mágicas pueden hacer tiradas de maña de esta Habilidad."
    },
    {
        key: "Sigilo",
        description: "Es muy importante saber cuándo se debe ser sigiloso para sobrevivir un día más. Desplazarse con el mayor de los silencios es esencial para pasar desapercibido, esconderse de algo o simplemente realizar un honroso ataque sorpresa por la espalda directo a la nuca del enemigo. Moverse con Sigilo requiere un extra de un PE en cada acción que se haga y divide por dos la VdM, pero ir con sigilo permite moverse y buscar trampas por la zona al mismo tiempo. Las tiradas de sigilo contra la Percepción del enemigo o la dificultad que el MJ proponga es de (1d10 + Sigilo + Des). Hay equipo que te penalizará por usarlo al ir en Sigilo o directamente no te dejará utilizar esta Habilidad."
    },
    {
        key: "Trampas",
        description: "En el camino de tu aventura, te encontrarás con ciertos obstáculos que podrían amputarte el pie en un instante, hacerte caer a un pozo con cocodrilos o que una sierra escondida te rebane en dos, pero también puedes ser tú el que coloque todas esas trampas para eliminar a tus amigos enemigos. Para poder detectar trampas enemigas podrás hacer una tirada de Percepción declarando la zona que mires. Si vas con Sigilo, el MJ podrá hacer las tiradas de forma automática para que puedan moverse más rápido, pero de forma un poco más insegura. Puedes hacer la tirada de Percepción declarando que buscas trampas (1d10 + Percepción) y, si la encuentras, podrás marcarla sin hacer tiradas de ningún tipo, para que el resto de personajes puedan verla o no llevársela puesta al regresar. También puedes desactivarla haciendo una tirada de (1d10 + Trampas + Sabiduría) y agregar cualquier bonificador como puede ser alguna herramienta de trampero contra la dificultad que el MJ disponga (ver Capítulo 9: el Mundo para trampas y tablas). Si al desactivarla fallas por 5 o más puntos en tu tirada, la trampa se activará. Si logras desactivarla, podrás hacer otra tirada para desarmarla y llevártela. Nuevamente la tirada es de (1d10 + Trampas + Sabiduría) y si fallas por 5 o más puntos en tu tirada, la trampa se romperá y quedará inutilizable."
    },
]